# docker-compose.yml
version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:80"

  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development