# docker-compose.dev.yml
version: "3.8"

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
